Repository kcp-dev/kcp-operator, pull requests merged in 2025-06, with the labels that each got.

#46 Add resource templates for customizing Deployments, Certificates and Services
  config/crd/bases/operator.kcp.io_frontproxies.yaml
  config/crd/bases/operator.kcp.io_kubeconfigs.yaml
  config/crd/bases/operator.kcp.io_rootshards.yaml
  config/crd/bases/operator.kcp.io_shards.yaml
  internal/resources/frontproxy/certificates.go
  internal/resources/frontproxy/deployment.go
  internal/resources/frontproxy/service.go
  internal/resources/kubeconfig/certificate.go
  internal/resources/rootshard/ca_certificates.go
  internal/resources/rootshard/certificates.go
  internal/resources/rootshard/deployment.go
  internal/resources/rootshard/service.go
  internal/resources/shard/certificates.go
  internal/resources/shard/deployment.go
  internal/resources/shard/service.go
  internal/resources/utils/certificates.go
  internal/resources/utils/deployments.go
  internal/resources/utils/services.go
  internal/resources/utils/shard.go
  sdk/apis/operator/v1alpha1/certmanager.go
  sdk/apis/operator/v1alpha1/common.go
  sdk/apis/operator/v1alpha1/frontproxy_types.go
  sdk/apis/operator/v1alpha1/kubeconfig_types.go
  sdk/apis/operator/v1alpha1/shard_types.go
  sdk/apis/operator/v1alpha1/zz_generated.deepcopy.go
  sdk/applyconfiguration/operator/v1alpha1/certificatemetadatatemplate.go
  sdk/applyconfiguration/operator/v1alpha1/certificateprivatekeytemplate.go
  sdk/applyconfiguration/operator/v1alpha1/certificatesecrettemplate.go
  sdk/applyconfiguration/operator/v1alpha1/certificatespectemplate.go
  sdk/applyconfiguration/operator/v1alpha1/certificatetemplate.go
  sdk/applyconfiguration/operator/v1alpha1/commonshardspec.go
  sdk/applyconfiguration/operator/v1alpha1/deploymentmetadatatemplate.go
  sdk/applyconfiguration/operator/v1alpha1/deploymentspectemplate.go
  sdk/applyconfiguration/operator/v1alpha1/deploymenttemplate.go
  sdk/applyconfiguration/operator/v1alpha1/frontproxyspec.go
  sdk/applyconfiguration/operator/v1alpha1/kubeconfigspec.go
  sdk/applyconfiguration/operator/v1alpha1/podmetadatatemplate.go
  sdk/applyconfiguration/operator/v1alpha1/podspectemplate.go
  sdk/applyconfiguration/operator/v1alpha1/podtemplatespec.go
  sdk/applyconfiguration/operator/v1alpha1/rootshardspec.go
  sdk/applyconfiguration/operator/v1alpha1/servicemetadatatemplate.go
  sdk/applyconfiguration/operator/v1alpha1/servicespectemplate.go
  sdk/applyconfiguration/operator/v1alpha1/servicetemplate.go
  sdk/applyconfiguration/operator/v1alpha1/shardspec.go
  sdk/applyconfiguration/operator/v1alpha1/x509subject.go
  sdk/applyconfiguration/utils.go
Labels: lgtm, dco-signoff: yes, kind/feature, approved, size/XXL, release-note

#48 Mount correct server certificate into front-proxy
  Makefile
  hack/ci/run-e2e-tests.sh
  internal/resources/frontproxy/certificates.go
  internal/resources/frontproxy/deployment.go
  internal/resources/rootshard/certificates.go
  test/e2e/frontproxies/frontproxies_test.go
  test/e2e/rootshards/rootshards_test.go
  test/e2e/shards/shards_test.go
  test/utils/deploy.go
  test/utils/utils.go
Labels: lgtm, kind/bug, dco-signoff: yes, approved, release-note, size/M

#52 disable admin battery in kcp
  internal/resources/rootshard/deployment.go
  internal/resources/shard/deployment.go
  internal/resources/utils/shard.go
Labels: lgtm, kind/bug, dco-signoff: yes, size/S, approved, release-note

#53 update to Go 1.24.4
  .prow.yaml
  Dockerfile
Labels: lgtm, dco-signoff: yes, kind/feature, size/S, approved, release-note

#56 fix typos
  .typos.toml
  test/e2e/shards/shards_test.go
Labels: lgtm, release-note-none, kind/cleanup, dco-signoff: yes, size/S, approved

#55 Create base/default contexts in kubeconfigs and extend samples
  config/samples/v1alpha1_frontproxy.yaml
  config/samples/v1alpha1_kubeconfig_frontproxy.yaml
  config/samples/v1alpha1_kubeconfig_rootshard.yaml
  config/samples/v1alpha1_kubeconfig_shard.yaml
  config/samples/v1alpha1_rootshard.yaml
  config/samples/v1alpha1_shard.yaml
  internal/controller/kubeconfig_controller.go
  internal/resources/kubeconfig/secret.go
Labels: lgtm, release-note-none, dco-signoff: yes, kind/feature, approved, size/L

#58 Add mkdocs documentation (docs.kcp.io/kcp-operator)
  .github/workflows/docs-gen-and-push.yaml
  Makefile
  Makefile.venv
  README.md
  config/samples/operator.kcp.io_v1alpha1_cacheserver.yaml
  config/samples/operator.kcp.io_v1alpha1_frontproxy.yaml
  config/samples/operator.kcp.io_v1alpha1_kubeconfig_frontproxy.yaml
  config/samples/operator.kcp.io_v1alpha1_kubeconfig_rootshard.yaml
  config/samples/operator.kcp.io_v1alpha1_kubeconfig_shard.yaml
  config/samples/operator.kcp.io_v1alpha1_rootshard.yaml
  config/samples/operator.kcp.io_v1alpha1_shard.yaml
  docs/.gitignore
  docs/content/.pages
  docs/content/README.md
  docs/content/contributing/architecture.md
  docs/content/contributing/continuous-integration/index.md
  docs/content/contributing/index.md
  docs/content/contributing/releasing.md
  docs/content/reference/.gitignore
  docs/content/reference/.pages
  docs/content/reference/index.md
  docs/content/setup/index.md
  docs/content/setup/quickstart.md
  docs/generators/crd-ref/config.yaml
  docs/generators/crd-ref/crd.template.md
  docs/generators/crd-ref/run-crd-ref-gen.sh
  docs/main.py
  docs/mkdocs.yml
  docs/overrides/favicons/android-chrome-192x192.png
  docs/overrides/favicons/android-chrome-512x512.png
  docs/overrides/favicons/apple-touch-icon.png
  docs/overrides/favicons/favicon-16x16.png
  docs/overrides/favicons/favicon-32x32.png
  docs/overrides/favicons/favicon.ico
  docs/overrides/favicons/mstile-150x150.png
  docs/overrides/icons/logo.svg
  docs/overrides/logo.svg
  docs/overrides/partials/outdated.html
  docs/overrides/partials/section-overview.html
  docs/overrides/stylesheets/crd.css
  docs/requirements.txt
  docs/scripts/deploy-docs.sh
  docs/scripts/serve-docs.sh
Labels: lgtm, release-note-none, dco-signoff: yes, approved, kind/documentation, size/XXL

#59 Bump golang.org/x/net to 0.38.0
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: lgtm, release-note-none, kind/cleanup, dco-signoff: yes, approved, size/M

#61 doc: Swap arguments places
  docs/content/setup/index.md
Labels: lgtm, release-note-none, dco-signoff: yes, approved, size/XS, kind/documentation

#60 Document correct release branch naming scheme
  docs/content/contributing/releasing.md
Labels: lgtm, release-note-none, dco-signoff: yes, approved, size/XS, kind/documentation
