Repository kcp-dev/kcp-operator, pull requests merged in 2025-01, with the labels that each got.

#4 ✨ Add initial reconcilers for `RootShard` and `Kubeconfig`
  .prow.yaml
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/common.go
  api/v1alpha1/kubeconfig_types.go
  api/v1alpha1/rootshard_types.go
  api/v1alpha1/shard_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kcp.io_cacheservers.yaml
  config/crd/bases/operator.kcp.io_rootshards.yaml
  config/crd/bases/operator.kcp.io_shards.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/samples/cert-manager/issuer.yaml
  config/samples/v1alpha1_kcpinstance.yaml
  config/samples/v1alpha1_kubeconfig.yaml
  config/samples/v1alpha1_rootshard.yaml
  go.mod
  go.sum
  hack/reconciling.yaml
  internal/controller/kubeconfig_controller.go
  internal/controller/kubeconfig_controller_test.go
  internal/controller/rootshard_controller.go
  internal/controller/rootshard_controller_test.go
  internal/controller/suite_test.go
  internal/reconciling/init.go
  internal/reconciling/zz_generated_reconcile.go
  internal/resources/kubeconfig/certificate.go
  internal/resources/kubeconfig/secret.go
  internal/resources/resources.go
  internal/resources/rootshard/ca_certificates.go
  internal/resources/rootshard/certificates.go
  internal/resources/rootshard/deployment.go
  internal/resources/rootshard/issuers.go
  internal/resources/rootshard/service.go
  test/crds/README.md
  test/crds/cert-manager.crds.yaml
Labels: lgtm, release-note-none, dco-signoff: yes, approved, size/XXL

#6 :bug: Add relevant RBAC markers for controllers
  config/rbac/role.yaml
  internal/controller/kubeconfig_controller.go
  internal/controller/rootshard_controller.go
Labels: lgtm, release-note-none, dco-signoff: yes, approved, size/M

#5 ✨ (re)write basic kind-based e2e tests
  .golangci.yml
  .prow.yaml
  go.mod
  hack/ci/build-image.sh
  hack/ci/run-e2e-tests.sh
  hack/ci/testdata/clusterissuer.yaml
  hack/ci/testdata/kustomization.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/rootshards/rootshards_test.go
  test/utils/utils.go
Labels: lgtm, release-note-none, size/XL, dco-signoff: yes, approved

#7 🐛 fix rootshard URL not pointing to its service
  api/v1alpha1/rootshard_types.go
  internal/resources/kubeconfig/secret.go
  test/utils/utils.go
Labels: lgtm, dco-signoff: yes, approved, size/XS, release-note

#8 ✨ bump to Go 1.23.4
  .golangci.yml
  .prow.yaml
  Dockerfile
  Makefile
Labels: lgtm, dco-signoff: yes, size/S, approved, release-note

#15 ✨ Add phase and owner references to RootShards
  api/v1alpha1/common.go
  api/v1alpha1/rootshard_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kcp.io_frontproxies.yaml
  config/crd/bases/operator.kcp.io_rootshards.yaml
  config/crd/bases/operator.kcp.io_shards.yaml
  internal/controller/rootshard_controller.go
Labels: lgtm, dco-signoff: yes, approved, size/L, release-note

#17 :sparkles: Refactor RootShard reconciler, add conditions to status
  api/v1alpha1/common.go
  api/v1alpha1/rootshard_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kcp.io_rootshards.yaml
  internal/controller/kubeconfig_controller.go
  internal/controller/rootshard_controller.go
  internal/resources/resources.go
  internal/resources/rootshard/ca_certificates.go
  internal/resources/rootshard/certificates.go
  internal/resources/rootshard/deployment.go
  internal/resources/rootshard/issuers.go
  internal/resources/rootshard/service.go
Labels: lgtm, dco-signoff: yes, approved, size/L, release-note

#18 :seedling: Bump golang.org/x/net to v0.33.0
  go.mod
  go.sum
Labels: lgtm, release-note-none, dco-signoff: yes, approved, size/M

#19 :seedling: Add labels to container image and refresh `build-image.sh`
  Dockerfile
  hack/ci/build-image.sh
Labels: lgtm, dco-signoff: yes, approved, release-note, size/M

#23 🐛 fix missing pod.ns.svc.cluster.local hostname in kcp server cert
  internal/resources/resources.go
  internal/resources/rootshard/certificates.go
Labels: lgtm, dco-signoff: yes, approved, size/XS, release-note

#20 :sparkles: Add FrontProxy controller
  README.md
  config/crd/bases/operator.kcp.io_frontproxies.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  config/samples/v1alpha1_frontproxy.yaml
  config/samples/v1alpha1_kubeconfig.yaml
  go.mod
  internal/controller/frontproxy_controller.go
  internal/controller/frontproxy_controller_test.go
  internal/controller/kubeconfig_controller.go
  internal/controller/rootshard_controller.go
  internal/resources/frontproxy/certificates.go
  internal/resources/frontproxy/configmap.go
  internal/resources/frontproxy/deployment.go
  internal/resources/frontproxy/path.go
  internal/resources/frontproxy/secrets.go
  internal/resources/frontproxy/service.go
  internal/resources/resources.go
  internal/resources/rootshard/deployment.go
  internal/resources/rootshard/issuers.go
  sdk/apis/operator/v1alpha1/common.go
  sdk/apis/operator/v1alpha1/frontproxy_types.go
  sdk/apis/operator/v1alpha1/rootshard_types.go
  sdk/apis/operator/v1alpha1/zz_generated.deepcopy.go
  sdk/applyconfiguration/operator/v1alpha1/frontproxy.go
  sdk/applyconfiguration/operator/v1alpha1/frontproxyspec.go
  sdk/applyconfiguration/operator/v1alpha1/frontproxystatus.go
  sdk/applyconfiguration/operator/v1alpha1/pathmappingentry.go
  sdk/applyconfiguration/operator/v1alpha1/servicespec.go
  sdk/applyconfiguration/utils.go
Labels: lgtm, ok-to-test, dco-signoff: yes, approved, size/XXL, release-note

#27 🌱 harmonize spelling of front-proxy, reduce public API
  README.md
  internal/controller/frontproxy_controller_test.go
  internal/resources/frontproxy/certificates.go
  internal/resources/frontproxy/configmap.go
  internal/resources/frontproxy/deployment.go
  internal/resources/frontproxy/path.go
  internal/resources/frontproxy/secrets.go
  internal/resources/resources.go
  sdk/apis/operator/v1alpha1/common.go
Labels: lgtm, dco-signoff: yes, approved, size/L, release-note

#26 ✨ Add volume revision labels for automatic rollouts
  internal/controller/frontproxy_controller.go
  internal/controller/frontproxy_controller_test.go
  internal/controller/kubeconfig_controller.go
  internal/controller/rootshard_controller.go
  internal/controller/rootshard_controller_test.go
  internal/controller/utils.go
  internal/kubernetes/metadata.go
  internal/reconciling/modifier/related_revisions.go
  internal/resources/frontproxy/certificates.go
  internal/resources/kubeconfig/certificate.go
  internal/resources/resources.go
  internal/resources/rootshard/ca_certificates.go
  internal/resources/rootshard/certificates.go
Labels: lgtm, dco-signoff: yes, approved, size/L, release-note
