Repository kcp-dev/kcp-operator, pull requests merged in 2025-09, with the labels that each got.

#88 fix: fix setting of volumes for authorization webhook configurations
  internal/resources/utils/authorization.go
Labels: lgtm, kind/bug, ok-to-test, dco-signoff: yes, approved, size/XS, release-note

#90 Use upstream approach and images to installing etcd
  Makefile
  docs/content/setup/quickstart.md
  hack/ci/run-e2e-tests.sh
  hack/ci/testdata/etcd/Chart.yaml
  hack/ci/testdata/etcd/templates/serviceaccount.yaml
  hack/ci/testdata/etcd/templates/services.yaml
  hack/ci/testdata/etcd/templates/statefulset.yaml
  hack/ci/testdata/etcd/values.yaml
  test/utils/deploy.go
Labels: lgtm, release-note-none, kind/cleanup, dco-signoff: yes, approved, size/L

#92 fix etcd TLS configuration not working
  internal/resources/utils/audit.go
  internal/resources/utils/authorization.go
  internal/resources/utils/shard.go
Labels: lgtm, kind/bug, dco-signoff: yes, approved, size/XS, release-note

#97 Update default kcp tag to v0.28.3
  internal/resources/resources.go
Labels: lgtm, dco-signoff: yes, kind/feature, approved, size/XS, release-note
